version: "3.8"

services:
  mc:
    restart: 'unless-stopped'
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "$PORT:25565"
    environment:
      MEMORY: "4G"
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "47.2.32"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
      # - ./modpack/:/modpacks
