---
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - $MUSIC:/music #optional
      - $DOWNLOADS:/downloads #optional
    ports:
      - $PORT:8686
    restart: unless-stopped
